import { expect, test } from 'bun:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runInNewContext } from 'node:vm';
import {
  ASSET_MODULE,
  ASSET_TYPES,
  assetBytes,
  assetMime,
  assetModule,
  importAsset,
  readAssets,
  saveAssets,
  validateAssets,
  type AssetLock,
  type ManagedAsset,
} from './index';

const binary = new Uint8Array([83, 83, 82, 67, 0, 1, 255, 128, 10, 42]);
const encode = (text: string) => new TextEncoder().encode(text);

// Exact external-asset output from the media-only helper shipped before assetBlob.
const previousTypes =
  '// Generated by soyLI.\nexport function assetUrl(id: string): Promise<string>;\nexport function releaseAssetUrls(): void;\n';
function previousHelper(entry: ManagedAsset) {
  return `// Generated by soyLI. Edit napplet.assets.json through soyli assets or the manager.

const assets = {${JSON.stringify(entry.id)}: {hash: ${JSON.stringify(entry.hash)}}};
const urls = new Map();
/** @param {string} id */
export async function assetUrl(id) {
  const entry = Object.hasOwn(assets, id) ? assets[id] : undefined;
  if (!entry) throw new PublishError('ASSET_INVALID', 'Unknown asset: ' + id);
  if (entry.url) return entry.url;
  if (!urls.has(id)) {
    const pending = window.napplet.resource.bytes('blossom:sha256:' + entry.hash).then(blob => URL.createObjectURL(blob));
    urls.set(id, pending);
    pending.catch(() => { if (urls.get(id) === pending) urls.delete(id); });
  }
  return urls.get(id);
}
export function releaseAssetUrls() {
  for (const value of urls.values()) value.then(url => URL.revokeObjectURL(url)).catch(() => {});
  urls.clear();
}
`;
}

function asset(id: string, mime: string, storage: ManagedAsset['storage']): ManagedAsset {
  return {
    id,
    mime,
    storage,
    hash: 'a'.repeat(64),
    path: `assets/${'a'.repeat(64)}.bin`,
    bytes: binary.length,
    license: 'MIT',
    source: '',
  };
}
function helper(
  assets: ManagedAsset[],
  embedded: string[] = [],
  resource: (url: string) => Promise<Blob> = async () => {
    throw new Error('Unexpected external resource');
  },
) {
  const lock: AssetLock = { version: 1, assets };
  const source = assetModule(lock);
  expect(source).not.toMatch(/\bfetch\s*\(/);
  const created: Blob[] = [];
  const revoked: string[] = [];
  const module = runInNewContext(
    source
      .replace(
        /^import embedded(\d+) from .*;$/gm,
        (_, index) => `const embedded${index} = ${JSON.stringify(embedded[Number(index)])};`,
      )
      .replace(/^export /gm, '') + '\n({ assetBlob, assetUrl, releaseAssetUrls })',
    {
      Blob,
      TextEncoder,
      atob,
      window: { napplet: { resource: { bytes: resource } } },
      URL: {
        createObjectURL(blob: Blob) {
          created.push(blob);
          return `blob:fixture-${created.length}`;
        },
        revokeObjectURL(url: string) {
          revoked.push(url);
        },
      },
    },
  ) as {
    assetBlob(id: string): Promise<Blob>;
    assetUrl(id: string): Promise<string>;
    releaseAssetUrls(): void;
  };
  return { ...module, created, revoked };
}

test('managed binary, JSON and text retain verified originals and require syncing old helpers', async () => {
  const root = await mkdtemp(join(tmpdir(), 'soy-asset-data-'));
  try {
    const samples = [
      { id: 'pack', bytes: binary, mime: 'application/octet-stream', extension: 'bin' },
      { id: 'scene', bytes: encode('{"scene":1}'), mime: 'application/json', extension: 'json' },
      { id: 'credits', bytes: encode('Illustration: Zoë'), mime: 'text/plain', extension: 'txt' },
    ];
    for (const sample of samples) {
      const imported = await importAsset(root, { ...sample, storage: 'external', license: 'MIT' });
      expect(imported.mime).toBe(sample.mime);
      expect(imported.path.endsWith('.' + sample.extension)).toBe(true);
      expect(await assetBytes(root, imported)).toEqual(sample.bytes);
    }
    await validateAssets(root);
    await Bun.write(join(root, ASSET_MODULE), '// Generated by soyLI.\n// Earlier helper\n');
    await expect(validateAssets(root)).rejects.toThrow('Run soyli assets sync');
    await saveAssets(root, await readAssets(root));
    await validateAssets(root);
    const pack = (await readAssets(root)).assets[0];
    await Bun.write(join(root, pack.path), new Uint8Array([...binary.slice(0, -1), 43]));
    await expect(assetBytes(root, pack)).rejects.toThrow('changed or is corrupt');
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('exact previous media helpers validate without rewriting, while mixed or modified pairs reject', async () => {
  const root = await mkdtemp(join(tmpdir(), 'soy-asset-legacy-'));
  const png = new Uint8Array(
    Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lS8AAAAASUVORK5CYII=',
      'base64',
    ),
  );
  try {
    const media = await importAsset(root, {
      id: 'cover',
      bytes: png,
      storage: 'external',
      license: 'MIT',
    });
    const currentModule = await Bun.file(join(root, ASSET_MODULE)).text();
    const currentTypes = await Bun.file(join(root, ASSET_TYPES)).text();
    const previousModule = previousHelper(media);
    await Bun.write(join(root, ASSET_MODULE), previousModule);
    await Bun.write(join(root, ASSET_TYPES), previousTypes);
    const before = await Bun.file(join(root, 'napplet.assets.json')).text();
    await validateAssets(root);
    expect(await Bun.file(join(root, ASSET_MODULE)).text()).toBe(previousModule);
    expect(await Bun.file(join(root, ASSET_TYPES)).text()).toBe(previousTypes);
    expect(await Bun.file(join(root, 'napplet.assets.json')).text()).toBe(before);
    for (const [module, types] of [
      [previousModule, currentTypes],
      [currentModule, previousTypes],
      [previousModule + '\n', previousTypes],
      [previousModule, previousTypes + '\n'],
    ]) {
      await Bun.write(join(root, ASSET_MODULE), module);
      await Bun.write(join(root, ASSET_TYPES), types);
      await expect(validateAssets(root)).rejects.toThrow('Run soyli assets sync');
    }
    await saveAssets(root, await readAssets(root));
    expect(await Bun.file(join(root, ASSET_MODULE)).text()).toBe(currentModule);
    expect(await Bun.file(join(root, ASSET_TYPES)).text()).toBe(currentTypes);
    await validateAssets(root);
    for (const bytes of [binary, encode('{"scene":1}'), encode('Plain credits')]) {
      await saveAssets(root, { version: 1, assets: [] });
      const data = await importAsset(root, {
        id: 'data',
        bytes,
        storage: 'external',
        license: 'MIT',
      });
      await Bun.write(join(root, ASSET_MODULE), previousHelper(data));
      await Bun.write(join(root, ASSET_TYPES), previousTypes);
      await expect(validateAssets(root)).rejects.toThrow('Run soyli assets sync');
    }
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('managed data keeps active-document policy and credential scanning', async () => {
  for (const text of [
    '<html>page</html>',
    '<svg/>',
    '<?xml version="1.0"?>',
    '<script>x</script>',
  ]) {
    expect(() => assetMime(encode(text))).toThrow('Resource policy blocks');
    try {
      assetMime(encode(text));
    } catch (error) {
      expect(error).toMatchObject({
        code: 'ASSET_INVALID',
        cause: { message: 'blocked-by-policy' },
      });
    }
  }
  const root = await mkdtemp(join(tmpdir(), 'soy-asset-secret-'));
  try {
    await expect(
      importAsset(root, {
        id: 'private-data',
        bytes: encode(JSON.stringify({ value: '-----BEGIN PRIVATE KEY-----' })),
        storage: 'external',
        license: 'MIT',
      }),
    ).rejects.toMatchObject({ code: 'SOURCE_SECRET' });
    expect((await readAssets(root)).assets).toEqual([]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('embedded Blob helper decodes binary, JSON and Unicode text without network access', async () => {
  const json = '{"title":"Café + 100%"}';
  const text = 'Zoë + 100% ✓';
  const urls = [
    'data:application/octet-stream;base64,' + Buffer.from(binary).toString('base64'),
    'data:application/octet-stream,%00%FF%80a',
    'data:application/json,' + encodeURIComponent(json),
    'data:text/plain;charset=utf-8,' + text.replace('%', '%25'),
  ];
  const api = helper(
    [
      asset('pack', 'application/octet-stream', 'embedded'),
      asset('raw', 'application/octet-stream', 'embedded'),
      asset('scene', 'application/json', 'embedded'),
      asset('credits', 'text/plain', 'embedded'),
    ],
    urls,
  );
  const blob = await api.assetBlob('pack');
  expect(blob.type).toBe('application/octet-stream');
  expect(new Uint8Array(await blob.arrayBuffer())).toEqual(binary);
  expect(await api.assetBlob('pack')).toBe(blob);
  expect(new Uint8Array(await (await api.assetBlob('raw')).arrayBuffer())).toEqual(
    new Uint8Array([0, 255, 128, 97]),
  );
  expect(await (await api.assetBlob('scene')).text()).toBe(json);
  expect(await (await api.assetBlob('credits')).text()).toBe(text);
  expect(await api.assetUrl('pack')).toBe(urls[0]);
  expect(api.created).toEqual([]);
  api.releaseAssetUrls();
  expect(await api.assetBlob('pack')).not.toBe(blob);
  await expect(api.assetBlob('toString')).rejects.toThrow('Unknown asset: toString');
  await expect(api.assetUrl('missing')).rejects.toThrow('Unknown asset: missing');
  const bad = helper([asset('bad', 'text/plain', 'embedded')], ['data:text/plain,%zz']);
  await expect(bad.assetBlob('bad')).rejects.toThrow('Invalid embedded asset data URL');
});

test('external Blob and URL helpers share resources, retry failures and release pending URLs', async () => {
  let requests = 0;
  let settle: (value: Blob) => void = () => {};
  const blob = new Blob([binary], { type: 'application/octet-stream' });
  const api = helper([asset('pack', blob.type, 'external')], [], async (url) => {
    requests++;
    expect(url).toBe('blossom:sha256:' + 'a'.repeat(64));
    if (requests === 1) throw new Error('Resource denied');
    if (requests === 2) return blob;
    return new Promise<Blob>((resolve) => {
      settle = resolve;
    });
  });
  const failed = await Promise.allSettled([api.assetBlob('pack'), api.assetUrl('pack')]);
  expect(failed.every((result) => result.status === 'rejected')).toBe(true);
  expect(requests).toBe(1);
  const [retryBlob, url, duplicateUrl] = await Promise.all([
    api.assetBlob('pack'),
    api.assetUrl('pack'),
    api.assetUrl('pack'),
  ]);
  expect(requests).toBe(2);
  expect(retryBlob).toBe(blob);
  expect(url).toBe(duplicateUrl);
  expect(api.created).toEqual([blob]);
  api.releaseAssetUrls();
  await Promise.resolve();
  expect(api.revoked).toEqual([url]);
  const pending = api.assetUrl('pack');
  await Promise.resolve();
  expect(requests).toBe(3);
  api.releaseAssetUrls();
  settle(blob);
  const pendingUrl = await pending;
  await Promise.resolve();
  expect(api.revoked).toEqual([url, pendingUrl]);
});
